import { notFound } from "next/navigation";
import { BackLink } from "@/components/back-link";
import { OpportunityTable } from "./_components/opportunity-table";
import { PageContainer, PageShell } from "@/components/page-shell";
import { Panel } from "@/components/ui/panel";
import { SectionLabel } from "@/components/ui/section-label";
import {
  getAllCombinedOpportunities,
  getMarketAuditSignals,
  getOpportunitiesBySignalId,
  getSignalById,
} from "@/lib/market-audit";

export default async function MarketAuditDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const signal = getSignalById(id);

  if (!signal) {
    notFound();
  }

  const signalOpportunities = getOpportunitiesBySignalId(signal.id);
  const allSignals = getMarketAuditSignals();
  const allCombinedOpportunities = getAllCombinedOpportunities();

  return (
    <PageShell className="px-6 py-10">
      <PageContainer className="max-w-4xl gap-8">
        <div className="flex items-center justify-between">
          <BackLink href="/market-audit">Back to list of signals</BackLink>
        </div>

        <div className="flex flex-col gap-8">
          <Panel className="p-8">
            <div className="flex flex-wrap items-center gap-3">
              <h1 className="text-2xl font-medium text-ink">{signal.title}</h1>
            </div>
            <p className="mt-3 max-w-4xl text-sm text-muted">{signal.summary}</p>
          </Panel>

          <Panel className="space-y-3 p-6 shadow-soft">
            <SectionLabel className="text-xs">
              Revenue opportunities (click to open)
            </SectionLabel>
            <OpportunityTable
              opportunities={signalOpportunities}
              allSignals={allSignals}
              allCombinedOpportunities={allCombinedOpportunities}
              currentSignalId={signal.id}
            />
          </Panel>

          <Panel className="p-6 text-sm text-muted">
            <div className="text-ink">How are these created?</div>
            <p className="mt-2">
              Overbase uses a &quot;world model&quot; to generate future
              scenarios. We imagine possible futures then analyze them to know
              what&apos;s likely to happen. This lets us forecast more
              accurately than backwards-facing techniques which miss what&apos;s
              important because they rely on lagging indicators. The potential
              revenue opportunities in this list were generated by our model. We
              picked a few higher probability opportunities from the tens of
              thousands our model created
            </p>
          </Panel>
        </div>
      </PageContainer>
    </PageShell>
  );
}
